import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./navbar";

const GeistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const GeistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Computer Buiding Helper App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        {/* Top Navigation Bar */}
        <NavigationBar />

        {/* Main Content */}
        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
}

